// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyWA8araxhVHrkxrk4PYX-OMyDmasz-s',
    appId: '1:155284277656:web:6d76d2403ce8a06cf483ed',
    messagingSenderId: '155284277656',
    projectId: 'yogayatra-72d32',
    authDomain: 'yogayatra-72d32.firebaseapp.com',
    storageBucket: 'yogayatra-72d32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGbkqqUhHAbxJkti6ejsJ6TeOqEqHUto',
    appId: '1:155284277656:android:0ad16104f80b6dc3f483ed',
    messagingSenderId: '155284277656',
    projectId: 'yogayatra-72d32',
    storageBucket: 'yogayatra-72d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClY4Hdkgx-n-95BuSFfx-d7ruab6d9_Fc',
    appId: '1:155284277656:ios:7054f47603d93719f483ed',
    messagingSenderId: '155284277656',
    projectId: 'yogayatra-72d32',
    storageBucket: 'yogayatra-72d32.appspot.com',
    iosBundleId: 'com.example.yogayatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClY4Hdkgx-n-95BuSFfx-d7ruab6d9_Fc',
    appId: '1:155284277656:ios:7054f47603d93719f483ed',
    messagingSenderId: '155284277656',
    projectId: 'yogayatra-72d32',
    storageBucket: 'yogayatra-72d32.appspot.com',
    iosBundleId: 'com.example.yogayatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfyWA8araxhVHrkxrk4PYX-OMyDmasz-s',
    appId: '1:155284277656:web:ea6522823e8c00c8f483ed',
    messagingSenderId: '155284277656',
    projectId: 'yogayatra-72d32',
    authDomain: 'yogayatra-72d32.firebaseapp.com',
    storageBucket: 'yogayatra-72d32.appspot.com',
  );
}
