// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3m47a97cWxPXDkmNzQip71JVL4awn5KI',
    appId: '1:577520367716:web:6e05bce0e540c2ead04771',
    messagingSenderId: '577520367716',
    projectId: 'yogayatra',
    authDomain: 'yogayatra.firebaseapp.com',
    storageBucket: 'yogayatra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQcUMY0MyjSxU2ibaEVIHTRES38rpP4n0',
    appId: '1:577520367716:android:802af511e97b7b60d04771',
    messagingSenderId: '577520367716',
    projectId: 'yogayatra',
    storageBucket: 'yogayatra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jqh2mb_MeHcjfb3K6uPqAJjiY0zyz8E',
    appId: '1:577520367716:ios:a83f510d2e421b3fd04771',
    messagingSenderId: '577520367716',
    projectId: 'yogayatra',
    storageBucket: 'yogayatra.firebasestorage.app',
    iosBundleId: 'com.sunkpo.yogayatramobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jqh2mb_MeHcjfb3K6uPqAJjiY0zyz8E',
    appId: '1:577520367716:ios:a83f510d2e421b3fd04771',
    messagingSenderId: '577520367716',
    projectId: 'yogayatra',
    storageBucket: 'yogayatra.firebasestorage.app',
    iosBundleId: 'com.sunkpo.yogayatramobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3m47a97cWxPXDkmNzQip71JVL4awn5KI',
    appId: '1:577520367716:web:d8b407ba06818e6fd04771',
    messagingSenderId: '577520367716',
    projectId: 'yogayatra',
    authDomain: 'yogayatra.firebaseapp.com',
    storageBucket: 'yogayatra.firebasestorage.app',
  );
}
